# Use Ubuntu as base image
FROM ubuntu

# Install necessary packages
RUN apt-get update && \
    apt-get install -y openssh-server

# Configure SSH server
RUN mkdir /var/run/sshd
RUN echo 'root:password' | chpasswd
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

EXPOSE 22


ENV SERVER_1_NAME server-1
ENV SERVER_2_NAME server-2
ENV SERVER_3_NAME server-3


COPY start.sh /start.sh
RUN chmod +x /start.sh

CMD ["/start.sh"]


